DATA VENTAS;
INPUT NAMES$ WEEK1-WEEK4;
TOTAL = WEEK1 + WEEK2 + WEEK3 + WEEK4;
CUMPLE = '';
DESPEDIDO = '';
IF TOTAL > 70 THEN DO;
	CUMPLE = 'S';
	DESPEDIDO = 'N';
END;

ELSE IF TOTAL < 70 THEN DO;
	CUMPLE = 'N';
	DESPEDIDO = 'S';
END;

/*
FORMAT PERFORMANCE $8.;
PERFORMANCE = '';
IF TOTAL >= 10 AND TOTAL < 30 THEN PERFORMANCE = 'LOW';
ELSE IF TOTAL >= 30 AND TOTAL < 50 THEN PERFORMANCE = 'MID';
ELSE IF TOTAL >= 50 AND TOTAL < 70 THEN PERFORMANCE = 'MID-HIGH';
ELSE PERFORMANCE = 'HIGH';
*/

/*CUMPLE = '';
DESPEDIDO = '';
IF TOTAL > 70 THEN CUMPLE = 'S';
ELSE CUMPLE = 'N';
IF TOTAL < 70 AND NAMES = 'JUAN' OR NAMES = 'PEDRO' THEN DESPEDIDO = 'S';
ELSE DESPEDIDO = 'N';
*/

NOMBRE2 = NAMES;

DATALINES;
JUAN 10 2 40 0
PEDRO 15 5 10 20
LUISA 50 10 0 30
MARIO 20 30 45 0
;
RUN;