/* Formatos */
	/* FECHAS */ 
DATA FECHAS;
FORMAT NOMBRE $10. FECHA DATE11.;
INPUT NOMBRE$ FECHA DATE11.;
/*FROMATO PARA FECHAS*/
DATALINES;
JUAN 1 APR 2018
PEDRO 10 DEC 2010
; RUN;

PROC PRINT DATA=FECHAS; FORMAT FECHA DATE.;RUN;
/* SE UTILIZA DATE. PARA MOSTRAR EL MINIMO DE CARACTERES PARA REPRESENTAR LA FECHA
AUNQUE TAMBIEN SE PUEDE USAR DATE7. DATE9. O DATE11.*/

	/* CADENAS */

DATA CERVEZA_LIBRE;
FORMAT MARCAS $9.;
/*SE MODIFICA YA QUE SAS TIENE POR DEFECTO UN LIMITE DE 8 CARACTERES*/
INPUT MARCAS$ ORIGEN$ PRECIO;
CARDS;
BUDWEISER USA 14.99
HEINEKEN NED 13.99
CORONA MEX 12.99
SAMADAMS USA 14.79
GUINESS IRE 17.99
;
RUN;